name: webdx
favicon: null
layout_spectrum: 0.05565725150518119
typography_spectrum: 0.11726118274964392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4980149297043681
  lightness: 0.006765640806406736
  saturation: 0.6578316511586308
  rhythmicContrast: 0.37698755180463195
purpose: []
